/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class I2Cpi */

#ifndef _Included_I2Cpi
#define _Included_I2Cpi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     I2Cpi
 * Method:    I2C_open
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_I2Cpi_I2C_1open
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     I2Cpi
 * Method:    I2C_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_I2Cpi_I2C_1close
  (JNIEnv *, jclass);

/*
 * Class:     I2Cpi
 * Method:    I2C_read_PCF8574
 * Signature: (BB[B)I
 */
JNIEXPORT jint JNICALL Java_I2Cpi_I2C_1read_1PCF8574
  (JNIEnv *, jclass, jbyte, jbyte, jbyteArray);

/*
 * Class:     I2Cpi
 * Method:    I2C_write_PCF8574
 * Signature: (BBB)I
 */
JNIEXPORT jint JNICALL Java_I2Cpi_I2C_1write_1PCF8574
  (JNIEnv *, jclass, jbyte, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
